### ISSUE TITLE
Shows error missing MSCVR80.dll missing from computer

### ISSUE THREAD

**Issue by priyankaprakasan** [GNUSim8085/GNUSim8085#12] opened 2016-12-07 15:13 UTC
I tried to install gnu8085-1.3.7 on windows 7 32bit machine. The installation went fine. But when I tried to open the app gets an error MSCVR.80.dll is missing, so couldn't open the application, any solution please..

**Comment by onkarshinde** [comment] 2017-01-14 14:10
Can you please confirm few things?
1. Exactly which exe file did you download to install?
2. Do you have the screenshot of the error? Perhaps other details in the error can help understand what is happening.

**Comment by priyankaprakasan** [comment] 2017-01-15 11:37
Hi Onkar,
I dont have the screen shot. But If I am correct the error was app failed
to run becoz of the file missing. Nothing more on that msg.

**Comment by onkarshinde** [comment] 2017-01-15 16:20
Looks like you may have to download Microsoft Visual C++ runtime.
https://www.microsoft.com/en-us/download/details.aspx?id=26347

Please refer to the details on this page
https://www.lifewire.com/how-to-fix-msvcr80-dll-not-found-or-missing-errors-2623805

**Comment by onkarshinde** [comment] 2017-01-29 14:10
Have you followed the instructions I provided? Please confirm if it fixed the issue.

**Comment by onkarshinde** [comment] 2017-02-18 15:24
Can you please confirm that the issue is fixed?

**Comment by priyankaprakasan** [comment] 2017-02-18 15:34
I didnt get enough  time to check it, but I will and let you know.

*Regards*

Priyanka
M.Tech in Computer and Information Science
Lecturer
Electrical Engineering Dept.
Anton de Kom University
Suriname

**Comment by onkarshinde** [comment] 2018-03-20 08:47
@priyankaprakasan Have you tried the resolution I suggested?

**Comment by onkarshinde** [comment] 2018-06-08 16:27
Closing the issue as I don't believe it is application issue. Possible resolution has been provided.

**Closed by onkarshinde** 2018-06-08 16:27 UTC
Labels: env
